//
//  SessionModelTests.swift
//  ResignalTests
//
//  Created by Kai Chen on 12/31/25.
//

import Testing
@testable import Resignal

@MainActor
struct SessionModelTests {

    @Test("Session auto-generates title from first question")
    func autoGeneratedTitle() async throws {
        let session = Session(
            title: "",
            inputText: "Q: What is your experience?\nA: I have many years of experience."
        )

        #expect(session.displayTitle.contains("What is your experience"))
    }

    @Test("Session uses custom title when set")
    func customTitle() async throws {
        let customTitle = "My Interview Session"
        let session = Session(
            title: customTitle,
            inputText: "Q: Tell me about yourself."
        )

        #expect(session.displayTitle == customTitle)
    }

    @Test("Input preview truncates long text")
    func inputPreviewTruncation() async throws {
        let longText = String(repeating: "A", count: 200)
        let session = Session(inputText: longText)

        #expect(session.inputPreview.count <= 103) // 100 chars + "..."
        #expect(session.inputPreview.hasSuffix("..."))
    }

    @Test("hasAnalysis returns correct state")
    func hasAnalysisState() async throws {
        let sessionWithoutAnalysis = Session(outputFeedback: "")
        let sessionWithAnalysis = Session(outputFeedback: "Some feedback")

        #expect(!sessionWithoutAnalysis.hasAnalysis)
        #expect(sessionWithAnalysis.hasAnalysis)
    }

    @Test("Rubric type conversion works correctly")
    func rubricTypeConversion() async throws {
        let session = Session(rubric: .softwareEngineering)

        #expect(session.rubricType == .softwareEngineering)

        session.rubricType = .productManagement
        #expect(session.rubric == Rubric.productManagement.rawValue)
    }
}

